export const PERMISSIONS = [
  { key: 'dashboard.read', name: 'View Dashboard', module: 'dashboard' },
  { key: 'users.read', name: 'View Users', module: 'users' },
  { key: 'users.write', name: 'Manage Users', module: 'users' },
  { key: 'users.delete', name: 'Delete Users', module: 'users' },
  { key: 'memberships.read', name: 'View Memberships', module: 'memberships' },
  { key: 'memberships.write', name: 'Manage Memberships', module: 'memberships' },
  { key: 'workouts.read', name: 'View Workouts', module: 'workouts' },
  { key: 'workouts.write', name: 'Manage Workouts', module: 'workouts' },
  { key: 'nutrition.read', name: 'View Nutrition', module: 'nutrition' },
  { key: 'nutrition.write', name: 'Manage Nutrition', module: 'nutrition' },
  { key: 'trainers.read', name: 'View Trainers', module: 'trainers' },
  { key: 'trainers.write', name: 'Manage Trainers', module: 'trainers' },
  { key: 'gallery.read', name: 'View Gallery', module: 'gallery' },
  { key: 'gallery.write', name: 'Manage Gallery', module: 'gallery' },
  { key: 'testimonials.read', name: 'View Testimonials', module: 'testimonials' },
  { key: 'testimonials.write', name: 'Manage Testimonials', module: 'testimonials' },
  { key: 'contact.read', name: 'View Contact Messages', module: 'contact' },
  { key: 'contact.write', name: 'Manage Contact Messages', module: 'contact' },
  { key: 'notifications.read', name: 'View Notifications', module: 'notifications' },
  { key: 'notifications.write', name: 'Send Notifications', module: 'notifications' },
  { key: 'reports.read', name: 'View Reports', module: 'reports' },
  { key: 'reports.export', name: 'Export Reports', module: 'reports' },
  { key: 'settings.read', name: 'View Settings', module: 'settings' },
  { key: 'settings.write', name: 'Manage Settings', module: 'settings' },
  { key: 'roles.read', name: 'View Roles', module: 'roles' },
  { key: 'roles.write', name: 'Manage Roles', module: 'roles' },
] as const

export type PermissionKey = (typeof PERMISSIONS)[number]['key']
